server:
  port: 8888

management:
  endpoint:
    health:
      show-details: always

feign:
  httpclient:
    disable-ssl-validation: true
    enabled: false
  okhttp:
    enabled: true

springdoc:
  api-docs:
    path: /holidays-api-docs
  swagger-ui:
    path: /holidays-swagger.html
  show-actuator: true

http_unstable_url: service-unstable:8080
